import angular from 'angular';

import appConfig  from './config/app.config';
import AppController from './config/app.controller'
import appRun     from './config/app.run';
import 'angular-ui-router';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './home';
import './service';


// Create and bootstrap application
const requires = [
    'ui.router',
    'templates',
    'app.services',
    'app.home'
];

// Mount on window for testing
window.app = angular.module('app', requires);
angular.module('app').config(appConfig);
angular.module('app').controller('AppController', AppController);
angular.module('app').run(appRun);
angular.bootstrap(document, ['app'], {
    strictDi: true
});
